<script setup lang="ts">
  defineProps({
    isLoading: {
      type: Boolean,
      default: false,
    },
  })
</script>
<template>
  <Transition name="loading-back">
    <div
      v-show="isLoading"
      class="absolute top-0 left-0 z-40 h-full w-full bg-black bg-opacity-90 backdrop-blur-sm"
    ></div>
  </Transition>
  <!-- eslint-disable-next-line vue/no-multiple-template-root -->
  <Transition name="loading-front">
    <div
      v-show="isLoading"
      class="absolute top-0 left-0 z-50 flex h-full w-full flex-col items-center justify-center"
    >
      <div class="loadingio-spinner-cube-ugek8813moc">
        <div class="ldio-l1mv0tq4ov">
          <div></div>
          <div></div>
          <div></div>
          <div></div>
        </div>
      </div>
      <span class="font-semibold text-white">{{ $t('please_wait') }}</span>
    </div>
  </Transition>
</template>

<style scoped>
  .loading-back-enter-active,
  .loading-back-leave-active {
    transition: opacity, 0.2s ease-in-out;
  }
  .loading-back-enter-from,
  .loading-back-leave-to {
    opacity: 0;
  }
  .loading-front-enter-active {
    transition: all, 0.5s ease-in-out;
  }
  .loading-front-leave-active {
    transition: all, 0.2s ease-in-out;
  }
  .loading-front-enter-from,
  .loading-front-leave-to {
    opacity: 0;
    transform: scale(0.9);
  }
  @keyframes ldio-l1mv0tq4ov {
    0% {
      transform: scale(1.1500000000000001);
    }
    100% {
      transform: scale(1);
    }
  }
  .ldio-l1mv0tq4ov div {
    position: absolute;
    width: 52.400000000000006px;
    height: 52.400000000000006px;
    top: 8.733333333333336px;
    left: 8.733333333333336px;
    background: #ffffff;
    animation: ldio-l1mv0tq4ov 1s cubic-bezier(0, 0.5, 0.5, 1) infinite;
    animation-delay: -0.3s;
  }
  .ldio-l1mv0tq4ov div:nth-child(2) {
    top: 8.733333333333336px;
    left: 69.86666666666666px;
    background: #e7e7e7;
    animation-delay: -0.2s;
  }
  .ldio-l1mv0tq4ov div:nth-child(3) {
    top: 69.86666666666666px;
    left: 8.733333333333336px;
    background: #b6b6b6;
    animation-delay: 0s;
  }
  .ldio-l1mv0tq4ov div:nth-child(4) {
    top: 69.86666666666666px;
    left: 69.86666666666666px;
    background: #d2d2d2;
    animation-delay: -0.1s;
  }
  .loadingio-spinner-cube-ugek8813moc {
    width: 131px;
    height: 131px;
    display: inline-block;
    overflow: hidden;
    background: none;
  }
  .ldio-l1mv0tq4ov {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
  }
  .ldio-l1mv0tq4ov div {
    box-sizing: content-box;
  }
  /* generated by https://loading.io/ */
</style>
